### ISSUE TITLE
Add server list

### ISSUE THREAD

**Issue by checksum0** [cashshuffle/cashshuffle-electron-cash-plugin#14] opened 2017-12-13 06:40 UTC
Add a server list to the plugin so that user quickly and easily find a server to shuffle. Also, place the server list well in sight into the plugin itself instead of into the settings window to help choosing a server quickly.

Maybe add a visual indicator to show user how full a shuffling round is (let's say they have 17 player out of 20) so they can select the best server and we maximize shuffling round.

Maybe it would be a possibility for server to talk to each other and send a shuffler data to another server that is cruelly lacking its last shuffler to complete a big round or something?

**Comment by clifordsymack** [comment] 2017-12-13 20:47
add server list. For now just a select. Then i will add additional parameters for server: amounts, pool size and so on.

**Comment by shravan-shandilya** [comment] 2017-12-15 05:51
The shuffle server drop-down is not getting populated on latest version of the code.

**Comment by clifordsymack** [comment] 2017-12-15 06:48
@shravan-shandilya how did you get this error? It is hanging or what?

**Comment by shravan-shandilya** [comment] 2017-12-15 15:55
I installed both electron cash and the plug-in following the instructions from REAFME.md .
It's not hanging,but when I click the drop-down no servers are listed. The drop-down doesn't expand.

**Comment by shravan-shandilya** [comment] 2017-12-15 15:57
Environment:
Ubuntu 16.04

**Comment by clifordsymack** [comment] 2017-12-15 18:31
@shravan-shandilya can you check the `servers.json` file in the `shuffle` folder? Is it exist?

**Comment by shravan-shandilya** [comment] 2017-12-19 14:33
@clifordsymack Sorry my bad,the problem was on [Ubuntu Gnome](https://ubuntugnome.org/). Just checked in another machine. Its working fine. Thanks

**Comment by ifol** [comment] 2017-12-21 12:00
I'm having the same issue as shravan-shandilya - the shuffle server drop-down is not getting populated.

OS is Kubuntu 17.04 and servers.json file seems ok

**Comment by clifordsymack** [comment] 2017-12-21 12:03
@ifol thanks for reply. I discovering it

**Comment by clifordsymack** [comment] 2018-05-02 16:52
Can't reproduce. Closing it.

**Closed by clifordsymack** 2018-05-02 16:52 UTC
